## Implementing Own Neural Network of One layer

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [70]:
def compute_cost(f_wb, y, m):
    # Cost Function
    cost = np.sum((f_wb - y)**2)
    cost = (1/(2*m)) * cost
    
    return cost

def gradient_descent(X, y, W, b, alpha, iteration):
    m = len(X)
    for i in range(iteration):
        f_wb = np.dot(X, W) + b
            
        d_dw = (1/m) * np.dot(X.T, f_wb - y)
        d_db = (1/m) * np.sum(f_wb - y)
        
        W = W - alpha * d_dw
        b = b - alpha * d_db
        
        cost = compute_cost(f_wb, y, m)
        if(i%100 == 0):
            print(f"Iteration = {i}, Cost = {cost}")
    
    return W, b

In [87]:
_input = np.array([[1, 2, 3]])
y = np.array([1])

In [88]:
W = np.zeros(_input.shape[1]) # One neuron
b = 0
alpha = 0.01
iteration = 1000

Weight, bias = gradient_descent(_input, y, W, b, alpha, iteration)

Iteration = 0, Cost = 0.5
Iteration = 100, Cost = 3.826089696766985e-15
Iteration = 200, Cost = 2.9341927888728416e-29
Iteration = 300, Cost = 9.860761315262648e-32
Iteration = 400, Cost = 9.860761315262648e-32
Iteration = 500, Cost = 9.860761315262648e-32
Iteration = 600, Cost = 9.860761315262648e-32
Iteration = 700, Cost = 9.860761315262648e-32
Iteration = 800, Cost = 9.860761315262648e-32
Iteration = 900, Cost = 9.860761315262648e-32


In [89]:
output = np.dot(_input, Weight) + bias

In [90]:
output

array([1.])

In [92]:
Weight, bias

(array([0.06666667, 0.13333333, 0.2       ]), 0.06666666666666671)

In [94]:
import numpy as np
import random

In [127]:
def Dense(input_, n):
    Weights = []
    biases = []
    for i in range(n):
        W = []
        for j in range(len(input_)):
            W.append(random.random())          
        Weights.append(W)
        biases.append(random.random())
    
    output = np.dot(Weights, input_) + biases
    return output

In [128]:
_input = [1, 2, 3, 2.5]
output = Dense(_input, 3)

print(f"Output = {output}")

Output = [5.26661893 4.57569148 5.45797235]


In [131]:
a1 = Dense(_input, 3) # First Hidden Layer
a2 = Dense(a1, 4)  # second Hidden Layer
a3 = Dense(a2, 3)  # Third Hidden Layer
output = Dense(a3, 1)  # Output Layer

output

array([17.27013989])