# import training dataset

In [1]:
from pickle import load, dump
import numpy as np
with open("X_train.pkl", "rb") as f:
    X_train = load(f)

In [2]:
with open("y_train.pkl", "rb") as f:
    y_train = load(f)

In [3]:
X_train[0], X_train.shape

(array([  53,    5,   69, 1174,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0]),
 (73996, 131))

In [4]:
lables = {'Positive': 0, 'Neutral': 1, 'Negative': 2, 'Irrelevant': 3}
y_train[:5], y_train.shape

(array([0, 0, 0, 0, 0], dtype=int64), (73996,))

# Train Model

In [7]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout, SimpleRNN

# Define the model
model = Sequential([
    Embedding(input_dim=74000, output_dim=2),
    SimpleRNN(32),
    Dense(4, activation='softmax')
])

# Compile the model
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# Print the model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 2)           148000    
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_1 (Dense)             (None, 4)                 132       
                                                                 
Total params: 149252 (583.02 KB)
Trainable params: 149252 (583.02 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
history = model.fit(X_train, y_train, epochs=10)

Epoch 1/10
 420/2313 [====>.........................] - ETA: 1:38 - loss: 1.3715 - accuracy: 0.2881

KeyboardInterrupt: 

In [ ]:
predict = model.predict(X_train)

In [ ]:
y_hat = [np.argmax(i) for i in predict]

In [ ]:
y_hat[:5]

[2, 2, 2, 2, 2]

In [ ]:
y_train[:5]

array([0, 0, 0, 0, 0])