# Connect google drive

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


# Import training dataset

In [1]:
from pickle import load, dump
import numpy as np
with open("/content/drive/MyDrive/Colab Notebooks/Sentiment Anyalasis/X_train.pkl", "rb") as f:
    X_train = load(f)

In [2]:
with open("/content/drive/MyDrive/Colab Notebooks/Sentiment Anyalasis/y_train.pkl", "rb") as f:
    y_train = load(f)

In [3]:
X_train[0], X_train.shape

(array([ 100,  152,   11,  121,    3,   45, 1674,   10,   24,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0, 

In [4]:
lables = {'Positive': 0, 'Neutral': 1, 'Negative': 2, 'Irrelevant': 3}
y_train[:5], y_train.shape

(array([0, 0, 0, 0, 0]), (73996,))

# Train Model

In [5]:
from keras.models import Sequential
from keras.layers import Embedding, Dense, SimpleRNN

# Define the model
model = Sequential([
    Embedding(input_dim=50000, output_dim=2),
    SimpleRNN(32),
    Dense(4, activation='softmax')
])

# Compile the model
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# Print the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 2)           100000    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 4)                 132       
                                                                 
Total params: 101252 (395.52 KB)
Trainable params: 101252 (395.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
history = model.fit(X_train, y_train, epochs=10)

Epoch 1/10
2313/2313 [==============================] - 90s 38ms/step - loss: 1.3687 - accuracy: 0.2983
Epoch 2/10
2313/2313 [==============================] - 91s 39ms/step - loss: 1.3679 - accuracy: 0.3037
Epoch 3/10
2313/2313 [==============================] - 84s 36ms/step - loss: 1.3536 - accuracy: 0.3303
Epoch 4/10
2313/2313 [==============================] - 84s 36ms/step - loss: 1.2663 - accuracy: 0.4245
Epoch 5/10
2313/2313 [==============================] - 84s 36ms/step - loss: 1.1410 - accuracy: 0.5256
Epoch 6/10
2313/2313 [==============================] - 84s 36ms/step - loss: 1.0503 - accuracy: 0.5782
Epoch 7/10
2313/2313 [==============================] - 83s 36ms/step - loss: 1.0000 - accuracy: 0.6015
Epoch 8/10
2313/2313 [==============================] - 84s 36ms/step - loss: 1.1192 - accuracy: 0.5366
Epoch 9/10
2313/2313 [==============================] - 84s 36ms/step - loss: 0.9351 - accuracy: 0.6346
Epoch 10/10
2313/2313 [==============================] - 84s 36m

In [13]:
history_ = model.fit(X_train, y_train, epochs=10)

Epoch 1/10
2313/2313 [==============================] - 81s 35ms/step - loss: 0.7746 - accuracy: 0.7200
Epoch 2/10
2313/2313 [==============================] - 82s 35ms/step - loss: 0.7176 - accuracy: 0.7496
Epoch 3/10
2313/2313 [==============================] - 79s 34ms/step - loss: 0.7151 - accuracy: 0.7474
Epoch 4/10
2313/2313 [==============================] - 81s 35ms/step - loss: 0.6603 - accuracy: 0.7751
Epoch 5/10
2313/2313 [==============================] - 79s 34ms/step - loss: 0.6378 - accuracy: 0.7843
Epoch 6/10
2313/2313 [==============================] - 80s 35ms/step - loss: 0.6475 - accuracy: 0.7783
Epoch 7/10
2313/2313 [==============================] - 79s 34ms/step - loss: 0.6385 - accuracy: 0.7819
Epoch 8/10
2313/2313 [==============================] - 80s 35ms/step - loss: 0.6344 - accuracy: 0.7847
Epoch 9/10
2313/2313 [==============================] - 80s 35ms/step - loss: 0.5845 - accuracy: 0.8080
Epoch 10/10
2313/2313 [==============================] - 80s 34m

In [14]:
predict = model.predict(X_train)

2313/2313 [==============================] - 22s 10ms/step


In [15]:
y_hat = [np.argmax(i) for i in predict]

In [16]:
y_hat[20:30]

[0, 0, 0, 0, 2, 2, 2, 2, 2, 2]

In [17]:
y_train[20:30]

array([0, 0, 0, 0, 2, 2, 2, 2, 2, 2])

# Save the Model And History

In [18]:
model.save("/content/drive/MyDrive/Colab Notebooks/Sentiment Anyalasis/model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [48]:
loss1 = history.history['loss']
loss2 = history_.history['loss']

newLoss = loss1
for l in loss2:
  newLoss.append(l)

# Round each float value to the fourth decimal place
newLoss = [round(num, 4) for num in newLoss]
newLoss

[1.3679,
 1.2663,
 1.141,
 1.0503,
 1.0,
 1.1192,
 0.9351,
 0.8304,
 0.7746,
 0.7176,
 0.7151,
 0.6603,
 0.6378,
 0.6475,
 0.6385,
 0.6344,
 0.5845,
 0.5538,
 0.7746,
 0.7176,
 0.7151,
 0.6603,
 0.6378,
 0.6475,
 0.6385,
 0.6344,
 0.5845,
 0.5538]

In [49]:
accuracy1 = history.history['accuracy']
accuracy2 = history_.history['accuracy']

newAccu = accuracy1
for ac in accuracy2:
  newAccu.append(ac)

# Round each float value to the fourth decimal place
newAccu = [round(num, 4) for num in newAccu]
newAccu

[0.2983,
 0.3037,
 0.3303,
 0.4245,
 0.5256,
 0.5782,
 0.6015,
 0.5366,
 0.6346,
 0.6908,
 0.72,
 0.7496,
 0.7474,
 0.7751,
 0.7843,
 0.7783,
 0.7819,
 0.7847,
 0.808,
 0.8189,
 0.72,
 0.7496,
 0.7474,
 0.7751,
 0.7843,
 0.7783,
 0.7819,
 0.7847,
 0.808,
 0.8189]

In [50]:
newHistory = {'loss': [newLoss], 'accuracy': [newAccu]}

In [51]:
newHistory

{'loss': [[1.3679,
   1.2663,
   1.141,
   1.0503,
   1.0,
   1.1192,
   0.9351,
   0.8304,
   0.7746,
   0.7176,
   0.7151,
   0.6603,
   0.6378,
   0.6475,
   0.6385,
   0.6344,
   0.5845,
   0.5538,
   0.7746,
   0.7176,
   0.7151,
   0.6603,
   0.6378,
   0.6475,
   0.6385,
   0.6344,
   0.5845,
   0.5538]],
 'accuracy': [[0.2983,
   0.3037,
   0.3303,
   0.4245,
   0.5256,
   0.5782,
   0.6015,
   0.5366,
   0.6346,
   0.6908,
   0.72,
   0.7496,
   0.7474,
   0.7751,
   0.7843,
   0.7783,
   0.7819,
   0.7847,
   0.808,
   0.8189,
   0.72,
   0.7496,
   0.7474,
   0.7751,
   0.7843,
   0.7783,
   0.7819,
   0.7847,
   0.808,
   0.8189]]}

In [53]:
import json

# Save the history to a JSON file
with open('/content/drive/MyDrive/Colab Notebooks/Sentiment Anyalasis/history.json', 'w') as json_file:
    json.dump(newHistory, json_file)